[tools]
lefthook = "2.0.16"

# lefthook hooks
<<<<<<< before updating
actionlint = "1.7.9"
=======
actionlint = "1.7.10"
bun = "1.3.8"
>>>>>>> after updating
"cargo:basefmt" = "0.1.0"
shellcheck = "0.11.0"
shfmt = "3.12.0"
